version: "3"

volumes:
  database:
    driver: local

services:
  backend:
    image: devchew/kjsbuddy-backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - database:/usr/src/app/data
    environment:
      - CORS_ORIGINS=https://localhost:9999,https://localhost:9997
  frontend:
    image: devchew/kjsbuddy-frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - 9999:80
    environment:
      - API_URL=http://localhost:3000

  admin:
    image: devchew/kjsbuddy-admin:latest
    container_name: admin
    restart: unless-stopped
    ports:
      - 9997:80
    environment:
      - API_URL=http://localhost:3000