version: "3"

volumes:
  database:
    driver: local

services:
  backend:
    build:
      context: ./dist/backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - database:/usr/src/app/data
    environment:
      - CORS_ORIGINS=http://localhost:8888,https://rajdex.pl

  frontend:
    build:
      context: ./dist/frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - 8888:80
    environment:
      - API_URL=http://backend:3000

  # backend:
  #   image: devchew/kjsbuddy-backend:master
  #   container_name: backend
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - database:/usr/src/app/data
  #   environment:
  #     - CORS_ORIGINS=https://rajdex.pl
  # frontend:
  #   image: devchew/kjsbuddy-frontend:master
  #   container_name: frontend
  #   restart: unless-stopped
  #   ports:
  #     - 8888:8080
  #   environment:
  #     - API_URL=http://api.rajdex.pl