version: "3"

volumes:
  database:
    driver: local

services:
  backend:
    image: devchew/kjsbuddy-backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - 9998:3000
    volumes:
      - database:/usr/src/app/data
    environment:
      - CORS_ORIGINS=https://localhost:9999,https://localhost:9997
  frontend:
    image: devchew/kjsbuddy-frontend:latest
    container_name: frontend
    restart: unless-stopped
    ports:
      - 9999:80
    environment:
      - API_URL=http://localhost:9998

  admin:
    image: devchew/kjsbuddy-admin:latest
    container_name: admin
    restart: unless-stopped
    ports:
      - 9997:80
    environment:
      - API_URL=http://localhost:9998

  landing:
    image: devchew/kjsbuddy-landing:latest
    container_name: landing
    restart: unless-stopped
    ports:
      - 9996:80
    environment:
      - MAIN_APP_URL=http://localhost:9997