version: "3"

volumes:
  database:
    driver: local

services:
  backend:
    build:
      context: ./dist/backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - database:/usr/src/app/data

  frontend:
    build:
      context: ./dist/frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - 8080:80