version: "3"

volumes:
  database:
    driver: local

services:
  backend:
    build:
      context: ./dist/backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - database:/usr/src/app/data
    environment:
      - CORS_ORIGINS=http://localhost:8888,http://localhost:9999

  frontend:
    build:
      context: ./dist/frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - 8888:80
    environment:
      - API_URL=http://backend:3000
  admin:
    build:
      context: ./dist/admin
      dockerfile: Dockerfile
    container_name: admin
    restart: unless-stopped
    ports:
      - 9999:80
    environment:
      - API_URL=http://backend:3000

  landing:
    build:
      context: ./dist/landing
      dockerfile: Dockerfile
    container_name: landing
    restart: unless-stopped
    ports:
      - 2137:80
    environment:
      - MAIN_APP_URL=http://backend:9999
