import createClient from "openapi-fetch";
import type { paths } from "./endpoints"; // generated by openapi-typescript
export type { components } from "./endpoints"; // generated by openapi-typescript

const baseUrl = import.meta.env.VITE_API_URL;

if (!baseUrl) {
  throw new Error(
    "VITE_API_URL is not defined in .env file. Please set it to the API URL.",
  );
}

export const client = createClient<paths>({ baseUrl });

export const createAuthClient = (token: string | null) =>
  createClient<paths>({
    baseUrl,
    headers: { Authorization: `Bearer ${token}` },
  });
