# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
    branches: master
    paths:
      - 'apps/**'
      - 'packages/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
        with:
          node-version-file: .nvmrc

      - name: enable corepack
        run: corepack enable

      - name: install packages
        run: pnpm install --frozen-lockfile

      - name: prepare dotenv
        run: cp ./apps/frontend/.env.substr ./apps/frontend/.env

      - name: prepare dotenv
        run: cp ./apps/admin/.env.substr ./apps/admin/.env

      - name: prepare dotenv
        run: cp ./apps/landing/.env.substr ./apps/landing/.env
        
      - name: build
        run: pnpm build

      - name: prune backend
        run: pnpm deploy --filter=./apps/backend --prod ./dist/backend

      - name: prune frontend
        run: pnpm deploy --filter=./apps/frontend --prod ./dist/frontend

      - name: prune admin
        run: pnpm deploy --filter=./apps/admin --prod ./dist/admin

      - name: 'Upload frontend'
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: ./dist/frontend
          
      - name: 'Upload backend'
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: ./dist/backend

      - name: 'Upload admin'
        uses: actions/upload-artifact@v4
        with:
          name: admin
          path: ./dist/admin
          
  push_frontend:
    needs: [build]
    name: Push Frontend image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download a frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: ./frontend
        

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: devchew/kjsbuddy-frontend
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.run_number }}
            type=raw,value=${{ github.sha }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_backend:
    needs: [build]
    name: Push Backend image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download a backend build
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: ./backend

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: devchew/kjsbuddy-backend
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.run_number }}
            type=raw,value=${{ github.sha }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_admin:
    needs: [build]
    name: Push admin image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download a admin build
        uses: actions/download-artifact@v4
        with:
          name: admin
          path: ./admin
        

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: devchew/kjsbuddy-admin
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.run_number }}
            type=raw,value=${{ github.sha }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./admin
          file: ./admin/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push_landing:
    needs: [build]
    name: Push landing image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download a landing build
        uses: actions/download-artifact@v4
        with:
          name: landing
          path: ./landing
        

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: devchew/kjsbuddy-landing
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.run_number }}
            type=raw,value=${{ github.sha }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./landing
          file: ./landing/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
